name: yusuf_yemek
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase Kütüphaneleri
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # UI ve Yardımcı Kütüphaneler
  google_maps_flutter: ^2.6.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  intl: ^0.20.2 # HATA İÇİN EKLENDİ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Asset'leri (görselleri) eklemek için:
  assets:
    - assets/images/
